# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Demo workflow cleanercode v0.2

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout branch from GitHub
      uses: actions/checkout@v2
    
    - name: Step 2 - Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: adopt
     
    - name: Step 3 - Set up a cache for Maven(Stephen)
      uses: actions/cache@v2
      with:
        path: 
          ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2-
        
    - name: Step 4 - Build Maven project(Alwyn)
      run:  mvn -B package --file mvnCleanerCodeDemo/pom.xml
    
  #  - name: Step 5 - Code check using SonarQube(Peter)
  #    run: mvn clean verify sonar:sonar -Dsonar.login=myAuthenticationToken
     
  #  - name: Step 6 - Junit test(Emil)
   
  #  - name: Step 7 - Security checking(Sai)

  #  - name: Step 8 - Performance management using Jmeter(Vinu)
  
    - name: Step 9 - Persist Wrokflow data as artifacts(Alwyn)
      run: mkdir staging1 && cp mvnCleanerCodeDemo/target/* staging1     
    - uses: actions/upload-artifact@v2
      with:
         name:  github-actions-artifact
         path:  staging1        
    
